spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: mymicroconfig
---
spring:
  profiles: pro
  application:
    name: mymicroconfig
---
spring:
  profiles: test
  application:
    name: mymicroconfig
