spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microconfig-test-dev
---
spring:
  profiles: pro
  application:
    name: microconfig-test-pro
---
spring:
  profiles: test
  application:
    name: microconfig-test-test
